#!/usr/bin/env bash

TARS_HOME="$HOME/AI/TARS"

source "$TARS_HOME/lib/model_manager.sh"

if [[ -n "$1" ]]; then
    MODEL=$(get_model_by_index "$1")
else
    MODEL=$(get_current_model)
fi

echo "Usando modelo: $MODEL"

hermes chat -m "$MODEL"
